[package]
name = "rustzone_ta"
version = "0.1.0"
authors = ["Eric Evenchick <eric@evenchick.com>"]

[dependencies]

[build-dependencies]
bindgen = "0.42.2"

[lib]
name = "ta"
crate-type = ["staticlib"]

[profile.release]
panic = "abort"
